"""Initial schema

Revision ID: 812c95e58141
Revises: 
Create Date: 2026-05-02 21:49:11.296966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '812c95e58141'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bdc_companies',
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_index(op.f('ix_bdc_companies_ticker'), 'bdc_companies', ['ticker'], unique=False)
    op.create_table('bdc_loans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bdc_ticker', sa.String(length=10), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('quarter', sa.String(length=6), nullable=True),
    sa.Column('borrower_name', sa.String(length=200), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('loan_type', sa.String(length=50), nullable=True),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('sofr_spread', sa.Float(), nullable=True),
    sa.Column('sofr_floor', sa.Float(), nullable=True),
    sa.Column('par_value', sa.Float(), nullable=True),
    sa.Column('fair_value', sa.Float(), nullable=True),
    sa.Column('fair_to_par_ratio', sa.Float(), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('is_non_accrual', sa.Boolean(), nullable=True),
    sa.Column('accession_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bdc_loans_bdc_ticker'), 'bdc_loans', ['bdc_ticker'], unique=False)
    op.create_index(op.f('ix_bdc_loans_quarter'), 'bdc_loans', ['quarter'], unique=False)
    op.create_table('bdc_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bdc_ticker', sa.String(length=10), nullable=False),
    sa.Column('bdc_name', sa.String(length=100), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('quarter', sa.String(length=6), nullable=True),
    sa.Column('nav_per_share', sa.Float(), nullable=True),
    sa.Column('stock_price', sa.Float(), nullable=True),
    sa.Column('nav_premium_discount_pct', sa.Float(), nullable=True),
    sa.Column('total_portfolio_fair_value', sa.Float(), nullable=True),
    sa.Column('non_accrual_rate_pct', sa.Float(), nullable=True),
    sa.Column('weighted_avg_yield', sa.Float(), nullable=True),
    sa.Column('new_originations', sa.Float(), nullable=True),
    sa.Column('repayments', sa.Float(), nullable=True),
    sa.Column('net_new_deployment', sa.Float(), nullable=True),
    sa.Column('debt_to_equity', sa.Float(), nullable=True),
    sa.Column('first_lien_pct', sa.Float(), nullable=True),
    sa.Column('total_loan_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filing_registry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bdc_ticker', sa.String(length=10), nullable=True),
    sa.Column('accession_number', sa.String(length=50), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('quarter', sa.String(length=6), nullable=True),
    sa.Column('form_type', sa.String(length=10), nullable=True),
    sa.Column('processing_status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accession_number')
    )
    op.create_table('macro_indicators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('series_id', sa.String(length=50), nullable=False),
    sa.Column('series_name', sa.String(length=100), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'series_id', name='uq_macro_date_series')
    )
    op.create_index(op.f('ix_macro_indicators_date'), 'macro_indicators', ['date'], unique=False)
    op.create_table('nlp_sentiment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bdc_ticker', sa.String(length=10), nullable=True),
    sa.Column('quarter', sa.String(length=6), nullable=True),
    sa.Column('call_date', sa.Date(), nullable=True),
    sa.Column('net_sentiment_score', sa.Float(), nullable=True),
    sa.Column('positive_chunks', sa.Integer(), nullable=True),
    sa.Column('negative_chunks', sa.Integer(), nullable=True),
    sa.Column('neutral_chunks', sa.Integer(), nullable=True),
    sa.Column('keyword_spread_compression', sa.Integer(), nullable=True),
    sa.Column('keyword_covenant_lite', sa.Integer(), nullable=True),
    sa.Column('keyword_dry_powder', sa.Integer(), nullable=True),
    sa.Column('keyword_deal_flow', sa.Integer(), nullable=True),
    sa.Column('keyword_non_accrual', sa.Integer(), nullable=True),
    sa.Column('keyword_origination', sa.Integer(), nullable=True),
    sa.Column('keyword_competition', sa.Integer(), nullable=True),
    sa.Column('raw_transcript_length', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nlp_sentiment')
    op.drop_index(op.f('ix_macro_indicators_date'), table_name='macro_indicators')
    op.drop_table('macro_indicators')
    op.drop_table('filing_registry')
    op.drop_table('bdc_summary')
    op.drop_index(op.f('ix_bdc_loans_quarter'), table_name='bdc_loans')
    op.drop_index(op.f('ix_bdc_loans_bdc_ticker'), table_name='bdc_loans')
    op.drop_table('bdc_loans')
    op.drop_index(op.f('ix_bdc_companies_ticker'), table_name='bdc_companies')
    op.drop_table('bdc_companies')
    # ### end Alembic commands ###
